# -*- coding: utf-8 -*-
"""Copy of phonepe pulse data extraction and cleaning.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/15KLYrtfFwEWRBUbpjYIzZ6jLIwxUMqEW
"""

!pip install streamlit
!pip install mysql.connector
!pip install plotly
!pip install os
!pip install gitpython

import pandas as pd
import mysql.connector as sql
import streamlit as st
import plotly.express as px
import os
import json
from PIL import Image

os.system("git clone https://github.com/phonepe/pulse.git")

x=os.listdir('/content/pulse/data')

path_agg_state='/content/pulse/data/aggregated/transaction/country/india/state'

path_agg_state='/content/pulse/data/aggregated/transaction/country/india/state'
agg_state_list=os.listdir(path_agg_state)
agg_state_list

#for aggregated transactions state wise
path_agg_state='/content/pulse/data/aggregated/transaction/country/india/state'
agg_state_list=os.listdir(path_agg_state)
agg_trans_dict={'State': [], 'Year': [], 'Quarter': [], 'Transaction_type': [], 'Transaction_count': [],'Transaction_amount': []}

for state in agg_state_list:
  agg_year_path=path_agg_state+'/'+state+'/'
  agg_year_list=os.listdir(agg_year_path)

  for year in agg_year_list:
    agg_q_path=agg_year_path+year+'/'
    agg_q_list=os.listdir(agg_q_path)

    for q in agg_q_list:
      agg_data_path=agg_q_path+q
      agg_trans_data=open(agg_data_path,'r')
      data_1=json.load(agg_trans_data)

      for i in data_1['data']['transactionData']:
        t_type = i['name']
        count = i['paymentInstruments'][0]['count']
        amount = i['paymentInstruments'][0]['amount']
        agg_trans_dict['State'].append(state)
        agg_trans_dict['Year'].append(year)
        agg_trans_dict['Quarter'].append(int(q[0]))
        agg_trans_dict['Transaction_type'].append(t_type)
        agg_trans_dict['Transaction_count'].append(count)
        agg_trans_dict['Transaction_amount'].append(amount)

agg_transactions=pd.DataFrame(agg_trans_dict)

#for aggregated users state wise
path_agg_user='/content/pulse/data/aggregated/user/country/india/state'
agg_user_state_list=os.listdir(path_agg_user)
agg_user_dict={'State': [], 'Year': [], 'Quarter': [], 'Brand_name': [], 'Count': [],'Percentage': []}

for state in agg_user_state_list:
  agg_year_path=path_agg_user+'/'+state+'/'
  agg_year_list=os.listdir(agg_year_path)

  for year in agg_year_list:
    agg_q_path=agg_year_path+year+'/'
    agg_q_list=os.listdir(agg_q_path)

    for q in agg_q_list:
      agg_data_path=agg_q_path+q
      agg_user_data=open(agg_data_path,'r')
      data_2=json.load(agg_user_data)
      try:

        for i in data_2['data']['usersByDevice']:
          name = i['brand']
          count = i['count']
          percentage = i["percentage"]
          agg_user_dict['Brand_name'].append(name)
          agg_user_dict['Count'].append(count)
          agg_user_dict['Percentage'].append(percentage)
          agg_user_dict['State'].append(state)
          agg_user_dict['Year'].append(year)
          agg_user_dict['Quarter'].append(int(q[0]))

      except:
        pass

#map transactions
path_map_trans='/content/pulse/data/map/transaction/hover/country/india/state'
map_state_list_t=os.listdir(path_map_trans)
map_trans_dict={'State': [], 'Year': [], 'Quarter': [], "region": [], 'Count': [],'Amount': []}

for state in map_state_list_t:
  agg_year_path=path_map_trans+'/'+state+'/'
  agg_year_list=os.listdir(agg_year_path)

  for year in agg_year_list:
    agg_q_path=agg_year_path+year+'/'
    agg_q_list=os.listdir(agg_q_path)

    for q in agg_q_list:
      agg_data_path=agg_q_path+q
      agg_user_data=open(agg_data_path,'r')
      data_3=json.load(agg_user_data)
      for i in data_3['data']["hoverDataList"]:
        name = i['name']
        count = i["metric"][0]['count']
        amount = i["metric"][0]['amount']
        map_trans_dict['State'].append(state)
        map_trans_dict['Year'].append(year)
        map_trans_dict['Quarter'].append(int(q[0]))
        map_trans_dict['region'].append(name)
        map_trans_dict['Count'].append(count)
        map_trans_dict['Amount'].append(amount)

map_transactions=pd.DataFrame(map_trans_dict)

#map users
path_map_user='/content/pulse/data/map/user/hover/country/india/state'
map_user_state_list=os.listdir(path_map_user)
map_user_dict={'State': [], 'Year': [], 'Quarter': [], 'Region': [], "RegisteredUsers": [], "AppOpens": []}

for state in map_user_state_list:
  year_path=path_map_user+'/'+state+'/'
  year_list=os.listdir(year_path)

  for year in year_list:
    q_path=year_path+year+'/'
    q_list=os.listdir(q_path)
    for q in q_list:
      data_path=q_path+q
      user_data=open(data_path,'r')
      data_4=json.load(user_data)

      for i in data_4['data']["hoverData"].items():
          district = i[0]
          registereduser = i[1]["registeredUsers"]
          appOpens = i[1]['appOpens']
          map_user_dict["Region"].append(district)
          map_user_dict["RegisteredUsers"].append(registereduser)
          map_user_dict["AppOpens"].append(appOpens)
          map_user_dict['State'].append(state)
          map_user_dict['Year'].append(year)
          map_user_dict['Quarter'].append(int(q[0]))

map_users=pd.DataFrame(map_user_dict)

#top transactions
path_top_trans='/content/pulse/data/top/transaction/country/india/state'
top_trans_list=os.listdir(path_top_trans)
top_trans_dict={'State': [], 'Year': [], 'Quarter': [], 'Pincode': [], 'Transaction_count': [],
            'Transaction_amount': []}
for state in top_trans_list:
  year_path=path_top_trans+'/'+state+'/'
  year_list=os.listdir(year_path)

  for year in year_list:
    q_path=year_path+year+'/'
    q_list=os.listdir(q_path)
    for q in q_list:
      data_path=q_path+q
      user_data=open(data_path,'r')
      data_5=json.load(user_data)

      for i in data_5['data']['pincodes']:
          name=i["entityName"]
          count=i["metric"]["count"]
          amount=i["metric"]["amount"]
          top_trans_dict["Pincode"].append(name)
          top_trans_dict["Transaction_count"].append(count)
          top_trans_dict["Transaction_amount"].append(amount)
          top_trans_dict['State'].append(state)
          top_trans_dict['Year'].append(year)
          top_trans_dict['Quarter'].append(int(q[0]))

top_transactions=pd.DataFrame(top_trans_dict)

#top users
path_top_user='/content/pulse/data/top/user/country/india/state'
top_user_state_list=os.listdir(path_top_user)
top_user_dict={'State': [], 'Year': [], 'Quarter': [], 'Pincode': [],'RegisteredUsers': []}

for state in top_user_state_list:
  year_path=path_top_user+'/'+state+'/'
  year_list=os.listdir(year_path)

  for year in year_list:
    q_path=year_path+year+'/'
    q_list=os.listdir(q_path)
    for q in q_list:
      data_path=q_path+q
      user_data=open(data_path,'r')
      data_6=json.load(user_data)

      for i in data_6['data']["pincodes"]:
          code= i["name"]
          registeredusers= i["registeredUsers"]
          top_user_dict["Pincode"].append(code)
          top_user_dict["RegisteredUsers"].append(registeredusers)
          top_user_dict['State'].append(state)
          top_user_dict['Year'].append(year)
          top_user_dict['Quarter'].append(int(q[0]))

top_users=pd.DataFrame(top_user_dict)

top_users.to_csv('top_users.csv',index=False)
top_transactions.to_csv('top_transactions.csv',index=False)
map_users.to_csv('map_users.csv',index=False)
map_transactions.to_csv('map_transactions.csv',index=False)
agg_users.to_csv('agg_users.csv',index=False)
agg_transactions.to_csv('agg_transactions.csv',index=False)





