# -*- coding: utf-8 -*-
"""Sql create and send.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1y6Ry1gmrpmhbfB0ku76eO7qkZUQo3OjT
"""

import sqlite3 as sql
import pandas as pd

conn=sql.connect('phonepe_data.db')
cur=conn.cursor()

conn.commit()

table_agg_trans="create table if not exists agg_transactions (State varchar(100), Year int, Quarter int, Transaction_type varchar(100), Transaction_count int, Transaction_amount double)"
cur.execute(table_agg_trans)
conn.commit
df_agg_trans=pd.read_csv('/content/agg_transactions (1).csv')
df_agg_trans.to_sql('agg_transactions',conn,if_exists='replace', index=False)
conn.commit()

table_agg_users="create table if not exists agg_users (State varchar(100), Year int, Quarter int, Brand_name varchar(100), Count int, Percentage double)"
cur.execute(table_agg_users)
conn.commit()
df_agg_users=pd.read_csv('/content/agg_users (1).csv')
df_agg_users.to_sql('agg_users',conn,if_exists='replace', index=False)
conn.commit()

table_map_users="create table if not exists map_users (State varchar(100), Year int, Quarter int, Region varchar(100), RegisteredUsers int, AppOpens int)"
cur.execute(table_map_users)
df_map_users=pd.read_csv('/content/map_users (1).csv')
df_map_users.to_sql('map_users',conn,if_exists='replace', index=False)
conn.commit()

table_map_trans="create table if not exists map_trans (State varchar(100), Year int, Quarter int, region int, Count int, Amount double)"
cur.execute(table_map_trans)
df_map_trans=pd.read_csv('/content/map_transactions (1).csv')
df_map_trans.to_sql('map_trans',conn,if_exists='replace',index=False)
conn.commit()

df_top_trans=pd.read_csv('/content/top_transactions (1).csv')
df_top_users=pd.read_csv('/content/top_users (1).csv')

table_top_trans="create table if not exists top_trans (State varchar(100), Year int, Quarter int, Pincode int, Transaction_count int, Transaction_amount double)"
cur.execute(table_top_trans)
df_top_trans.to_sql('top_trans',conn,if_exists='replace',index=False)
conn.commit()

table_top_users="create table if not exists top_users (State varchar(100), Year int, Quarter int, Pincode int, RegisteredUsers int)"
cur.execute(table_top_users)
df_top_users.to_sql('top_users',conn,if_exists='replace',index=False)
conn.commit()

